public enum SkillName {
    OVERALL, ATTACK, DEFENCE, STRENGTH,
    HITPOINTS, RANGED, PRAYER, MAGIC,
    COOKING, WOODCUTTING, FLETCHING,
    FISHING, FIREMAKING, CRAFTING, SMITHING,
    MINING, HERBLORE, AGILITY, THEIVING, SLAYER,
    FARMING, RUNECRAFT, HUNTER, CONSTRUCTION, SAILING
}